labels: ["question"]
body:
  - type: textarea
    id: question
    attributes:
      label: Your question
    validations:
      required: true
  - type: input
    id: setup
    attributes:
      label: Your setup
      placeholder: "Linux or Windows, container or process, agent framework"
